# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
  servlet:
    context-path: /winchem

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.winchem.aftersale.*.entity
#日志输出,true输出，false不输出
  sql:
    show: true
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: true
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    
#单数据源配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    db1:
      dbUrl: jdbc:mysql://rm-2zeg5irz2v3wse904xo.mysql.rds.aliyuncs.com:3306/business_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driverClassName: com.mysql.cj.jdbc.Driver
      username: winchem_test
      password: Winchemtest2020
      initialSize: 20
      maxActive: 100
      minIdle: 20
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 30
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      maxEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      type: com.alibaba.druid.pool.DruidDataSource
#多数据源配置信息2
#    db2:
#      driverClassName: com.mysql.cj.jdbc.Driver
#      #dbUrl: jdbc:mysql://rm-2zes52x5im855av8ro.mysql.rds.aliyuncs.com:3306/winchem_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#      #dbUrl: jdbc:mysql://192.168.3.2:3306/winchem_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#      dbUrl: jdbc:mysql://rm-2zes52x5im855av8ro.mysql.rds.aliyuncs.com:3306/winchem_lucky_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#      dbUrl: jdbc:mysql://rm-2zes52x5im855av8ro.mysql.rds.aliyuncs.com:3306/winchem_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#      username: report_form
#      password: Winchem_report2019
#      initialSize: 20
#      maxActive: 100
#      minIdle: 20
#      maxWait: 60000
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 30
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 30000
#      maxEvictableIdleTimeMillis: 60000
#      validationQuery: SELECT 1 FROM DUAL
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      filters: stat,wall
# 日志打印
#logging:
  level:
    com.winchem: DEBUG

#redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        min-idle: 0
        # 连接池中的最小空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

